name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: CHECKOUT
        uses: actions/checkout@v2

      - name: 0.a Installing dependencies
        run: sudo apt-get install imagemagick fdupes
      
      - name: 0.b Check and remove duplicate files
        run: |
          cd img/paintings/
          fdupes -dN .
      
      - name: 1. Reducing image sizes to 1920px
        run: |
          find img/paintings/ -name '*.jpg' | while IFS= read -r f; do
              width=$(identify -format '%w' "$f")
              height=$(identify -format '%h' "$f")
              if [ "$width" -gt 1920 ] && [ "$height" -gt 1920 ]; then
                [ "$width" -ge "$height" ] && convert -thumbnail "1920" "$f" "$f" || convert -thumbnail "x1920" "$f" "$f"
              fi
          done

      - name: 2. Generating suffixes for image files
        run: |
          find img/paintings/ -name '*.jpg' | while IFS= read -r f; do
            nf="${f%-*}.jpg"
            mv "$f" "$nf"
          done

          find img/paintings/ -name '*.jpg' | while IFS= read -r f; do
            suffix=$(identify -format '%wx%h' "$f")
            mv "$f" "${f%.*}-$suffix.jpg"
          done

      - name: 3. Generating thumbnails
        run: |
          dir_thumb="img/thumb"
          mkdir -p "$dir_thumb"
          w=200
          find img/paintings/ -name '*.jpg' | while IFS= read -r f; do
            nf="$dir_thumb/thumb.${f##*/}"
            convert -thumbnail "$w" "$f" "$nf"
          done

      - name: 4. Writing paintings.csv-file
        run: |
          fil_csv="_data/paintings.csv"
          echo "name,orig,thumb" > "$fil_csv"
          find img/paintings/ -name '*.jpg' | while IFS= read -r f; do
            raw=$(readlink -f "$f")
            filename="${raw##*/}"
            name="${filename%.*}"
            orig="/img/paintings/$filename"
            thumb="/img/thumb/thumb.${name}.jpg"
            echo "$name,$orig,$thumb" >> "$fil_csv"
          done

      - name: 5. Commit automated preparation
        run: |
          git config --global user.name 'BOT'
          git config --global user.email 'piano337@users.noreply.github.com'
          git add .
          git commit -m "#Bot: automated prepScripts"
          git push
